version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '2.9.1'
      MAINTAINER: '@akshat28'
      VENDOR: 'asus'
      CODENAME: 'X00T'
      FLAVOR: 'eng'
      PB_OFFICIAL: 'true'
      CHANGELOG: |
        - Updated prebuilt kernel
        - Updated encrytion blobs from stock
        - Fixed Stock rom flashing
        - For otg while keeping the otg connected in recovery reboot to recovery once again from the menu in the recovery
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 'android-9.0'
          context: org-global
